eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.30.243:8761/eureka
      non-secure-port: 80
  instance:
    hostname: 192.168.30.243
